package com.database.controller;

import com.database.service.GlycanService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

import com.database.service.GlycanService;
        
@Controller // This means that this class is a Controller
public class GlycanController {

    @Autowired
    // This means to get the bean which is auto-generated by Spring
    // We will use an glycanService for each
    GlycanService glycanService;

    //	display list of glycans
    @GetMapping("/MySQLTableForGlycansAndCCS")
    // This means that this method will be executed when user sends GET Requests to "/"
    // In our case, "http://localhost:8080/"
    public String viewHomePage(Model model) {

            //	We can use this attribute "listGlycans" to perform server-side rendering of the HTML with using Thymeleaf.
            //	We set all glycans data to "listGlycans"
            model.addAttribute("listGlycans", glycanService.getAllGlycans());

            //		shows the index.html template:
            return "index";
            
            
    }
    
  
    
}